version: '3.1'

services:

  scaper:
    image: scraper/demo
    environment:
      HOST: dbMysql
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: password
      DATABASE: scraped_results
    command: npm run start:docker
    networks:
      - nodejs-recursive-scraper_test

networks:
  nodejs-recursive-scraper_test:
    external: true
