version: '3.1'

services:

  dbMysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scraped_results
    command: --init-file /data/init.sql
    volumes:
        - ./init.sql:/data/init.sql
        - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080